server:
  ip: "192.168.3.67"
  user: "admin"
  password: "admin@123"


wifi:
  ssid: "mirafra"
  password: "Skdlt032"
  security_modes:
    - wpa1
    - wpa2
    - wpa3
  interface: "wlan0"
  channel: 6
  band: "5GHz"
  ip: "192.168.3.63"

wifiwrong_password:
  password: "vishwa@123"